#%RAML 1.0
title: Sandbox
version: v1
documentation:
- title: Introduction
  content: |
    This is the API documentation for the sandbox application.
mediaType: application/json
baseUri: http://localhost:8090/{version}/
